In [1]:
import pandas as pd
from datetime import datetime, date

pd.set_option('display.max_columns', 200)

In [2]:
games = pd.read_json('games.json')
games.head()

,age,date,defense_interception_touchdowns,defense_interception_yards,defense_interceptions,defense_sacks,defense_safeties,defense_tackle_assists,defense_tackles,field_goal_attempts,...,punting_yards,receiving_receptions,receiving_targets,receiving_touchdowns,receiving_yards,rushing_attempts,rushing_touchdowns,rushing_yards,team,year
0,23-120,1990-09-09,0,0,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,SEA,1990
1,23-127,1990-09-16,0,0,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,SEA,1990
2,23-134,1990-09-23,0,0,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,SEA,1990
3,23-142,1990-10-01,0,0,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,SEA,1990
4,23-148,1990-10-07,0,0,0,0.0,0,0,0,0,...,0,0,0,0,0,0,0,0,SEA,1990

In [3]:
players = pd.read_json('players.json')
players.head()

,birth_date,birth_place,college,current_salary,current_team,death_date,draft_position,draft_round,draft_team,draft_year,height,high_school,hof_induction_year,name,player_id,position,weight
0,1967-05-12,"Bay City, TX",Baylor,None,None,None,34.0,2.0,Seattle Seahawks,1990.0,6-0,"Van Vleck, TX",NaN,Robert Blackmon,1809,DB,208.0
1,1970-07-20,"Louisville, KY",Kentucky,None,None,None,85.0,4.0,Seattle Seahawks,1993.0,6-3,"Holy Cross, KY",NaN,Dean Wells,23586,LB,248.0
2,1990-08-14,"Newton, MA",Oregon,"1,075,000",Miami Dolphins,None,46.0,2.0,Buffalo Bills,2013.0,6-3,"Los Gatos, CA",NaN,Kiko Alonso,355,ILB,238.0
3,1948-04-22,"Dallas, TX",North Texas,None,None,1999-10-15,126.0,5.0,New Orleans Saints,1970.0,6-2,"W.W. Samuell, TX",NaN,Steve Ramsey,18182,QB,210.0
4,1988-02-27,"Neptune, NJ",Miami (FL),None,None,None,NaN,NaN,None,NaN,6-0,"Neptune, NJ",NaN,Cory Nelms,16250,CB,195.0

In [4]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1024164 entries, 0 to 1024163
Data columns (total 46 columns):
age                                1024164 non-null object
date                               1024164 non-null datetime64[ns]
defense_interception_touchdowns    1024164 non-null int64
defense_interception_yards         1024164 non-null int64
defense_interceptions              1024164 non-null int64
defense_sacks                      1024164 non-null float64
defense_safeties                   1024164 non-null int64
defense_tackle_assists             1024164 non-null int64
defense_tackles                    1024164 non-null int64
field_goal_attempts                1024164 non-null int64
field_goal_makes                   1024164 non-null int64
game_location                      1024164 non-null object
game_number                        1024164 non-null int64
game_won                           1024164 non-null bool
kick_return_attempts               1024164 non-null int64
kick_return_touchdowns             1024164 non-null int64
kick_return_yards                  1024164 non-null int64
opponent                           1024164 non-null object
opponent_score                     1024164 non-null int64
passing_attempts                   1024164 non-null int64
passing_completions                1024164 non-null int64
passing_interceptions              1024164 non-null int64
passing_rating                     1024164 non-null float64
passing_sacks                      1024164 non-null int64
passing_sacks_yards_lost           1024164 non-null int64
passing_touchdowns                 1024164 non-null int64
passing_yards                      1024164 non-null int64
player_id                          1024164 non-null int64
player_team_score                  1024164 non-null int64
point_after_attemps                1024164 non-null int64
point_after_makes                  1024164 non-null int64
punt_return_attempts               1024164 non-null int64
punt_return_touchdowns             1024164 non-null int64
punt_return_yards                  1024164 non-null int64
punting_attempts                   1024164 non-null int64
punting_blocked                    1024164 non-null int64
punting_yards                      1024164 non-null int64
receiving_receptions               1024164 non-null int64
receiving_targets                  1024164 non-null int64
receiving_touchdowns               1024164 non-null int64
receiving_yards                    1024164 non-null int64
rushing_attempts                   1024164 non-null int64
rushing_touchdowns                 1024164 non-null int64
rushing_yards                      1024164 non-null int64
team                               1024164 non-null object
year                               1024164 non-null int64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(38), object(4)
memory usage: 352.6+ MB

In [5]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25043 entries, 0 to 25042
Data columns (total 17 columns):
birth_date            24879 non-null object
birth_place           24151 non-null object
college               24893 non-null object
current_salary        1765 non-null object
current_team          1881 non-null object
death_date            6542 non-null object
draft_position        15041 non-null float64
draft_round           15041 non-null float64
draft_team            15041 non-null object
draft_year            15041 non-null float64
height                24788 non-null object
high_school           23889 non-null object
hof_induction_year    0 non-null float64
name                  25043 non-null object
player_id             25043 non-null int64
position              25043 non-null object
weight                24927 non-null float64
dtypes: float64(5), int64(1), object(11)
memory usage: 3.2+ MB

In [6]:
#combine players and games, note - inner join by default
player_games = games.merge(players, on='player_id')
player_games.head()

,age,date,defense_interception_touchdowns,defense_interception_yards,defense_interceptions,defense_sacks,defense_safeties,defense_tackle_assists,defense_tackles,field_goal_attempts,...,draft_position,draft_round,draft_team,draft_year,height,high_school,hof_induction_year,name,position,weight
0,23-120,1990-09-09,0,0,0,0.0,0,0,0,0,...,34.0,2.0,Seattle Seahawks,1990.0,6-0,"Van Vleck, TX",NaN,Robert Blackmon,DB,208.0
1,23-127,1990-09-16,0,0,0,0.0,0,0,0,0,...,34.0,2.0,Seattle Seahawks,1990.0,6-0,"Van Vleck, TX",NaN,Robert Blackmon,DB,208.0
2,23-134,1990-09-23,0,0,0,0.0,0,0,0,0,...,34.0,2.0,Seattle Seahawks,1990.0,6-0,"Van Vleck, TX",NaN,Robert Blackmon,DB,208.0
3,23-142,1990-10-01,0,0,0,0.0,0,0,0,0,...,34.0,2.0,Seattle Seahawks,1990.0,6-0,"Van Vleck, TX",NaN,Robert Blackmon,DB,208.0
4,23-148,1990-10-07,0,0,0,0.0,0,0,0,0,...,34.0,2.0,Seattle Seahawks,1990.0,6-0,"Van Vleck, TX",NaN,Robert Blackmon,DB,208.0

In [7]:
cols = player_games.columns.tolist()
cols

['age',
 'date',
 'defense_interception_touchdowns',
 'defense_interception_yards',
 'defense_interceptions',
 'defense_sacks',
 'defense_safeties',
 'defense_tackle_assists',
 'defense_tackles',
 'field_goal_attempts',
 'field_goal_makes',
 'game_location',
 'game_number',
 'game_won',
 'kick_return_attempts',
 'kick_return_touchdowns',
 'kick_return_yards',
 'opponent',
 'opponent_score',
 'passing_attempts',
 'passing_completions',
 'passing_interceptions',
 'passing_rating',
 'passing_sacks',
 'passing_sacks_yards_lost',
 'passing_touchdowns',
 'passing_yards',
 'player_id',
 'player_team_score',
 'point_after_attemps',
 'point_after_makes',
 'punt_return_attempts',
 'punt_return_touchdowns',
 'punt_return_yards',
 'punting_attempts',
 'punting_blocked',
 'punting_yards',
 'receiving_receptions',
 'receiving_targets',
 'receiving_touchdowns',
 'receiving_yards',
 'rushing_attempts',
 'rushing_touchdowns',
 'rushing_yards',
 'team',
 'year',
 'birth_date',
 'birth_place',
 'college',
 'current_salary',
 'current_team',
 'death_date',
 'draft_position',
 'draft_round',
 'draft_team',
 'draft_year',
 'height',
 'high_school',
 'hof_induction_year',
 'name',
 'position',
 'weight']

In [10]:
# remove defense & special teams stat columns, other irrelevant columns, and reorder columns
cols = [
 'player_id',
 'name',
 'team',
 'position',
 'age',
 'date',
 'year',
 'birth_date',
 'birth_place',
 'college',
 'current_salary',
 'current_team',
 'death_date',
 'draft_position',
 'draft_round',
 'draft_team',
 'draft_year',
 'height',
 'high_school',
 'hof_induction_year',
 'weight',
 'field_goal_attempts',
 'field_goal_makes',
 'game_location',
 'game_number',
 'game_won',
 'opponent',
 'opponent_score',
 'passing_attempts',
 'passing_completions',
 'passing_interceptions',
 'passing_rating',
 'passing_sacks',
 'passing_sacks_yards_lost',
 'passing_touchdowns',
 'passing_yards',
 'player_team_score',
 'point_after_attemps',
 'point_after_makes',
 'receiving_receptions',
 'receiving_targets',
 'receiving_touchdowns',
 'receiving_yards',
 'rushing_attempts',
 'rushing_touchdowns',
 'rushing_yards']

In [11]:
player_games = player_games[cols]
player_games.head()

,player_id,name,team,position,age,date,year,birth_date,birth_place,college,...,player_team_score,point_after_attemps,point_after_makes,receiving_receptions,receiving_targets,receiving_touchdowns,receiving_yards,rushing_attempts,rushing_touchdowns,rushing_yards
0,1809,Robert Blackmon,SEA,DB,23-120,1990-09-09,1990,1967-05-12,"Bay City, TX",Baylor,...,0,0,0,0,0,0,0,0,0,0
1,1809,Robert Blackmon,SEA,DB,23-127,1990-09-16,1990,1967-05-12,"Bay City, TX",Baylor,...,13,0,0,0,0,0,0,0,0,0
2,1809,Robert Blackmon,SEA,DB,23-134,1990-09-23,1990,1967-05-12,"Bay City, TX",Baylor,...,31,0,0,0,0,0,0,0,0,0
3,1809,Robert Blackmon,SEA,DB,23-142,1990-10-01,1990,1967-05-12,"Bay City, TX",Baylor,...,31,0,0,0,0,0,0,0,0,0
4,1809,Robert Blackmon,SEA,DB,23-148,1990-10-07,1990,1967-05-12,"Bay City, TX",Baylor,...,33,0,0,0,0,0,0,0,0,0

In [14]:
# Creating the target variable

# Create columns for fantasy points based on ESPN standard scoring format
player_games['fp_receiving_touchdowns'] = player_games.apply(lambda row: row['receiving_touchdowns'] * 6, axis=1)
player_games['fp_receiving_receptions'] = player_games.apply(lambda row: row['receiving_receptions'] * .5, axis=1)
player_games['fp_receiving_yards'] = player_games.apply(lambda row: row['receiving_yards'] * .1, axis=1)
player_games['fp_rushing_touchdowns'] = player_games.apply(lambda row: row['rushing_touchdowns'] * 6, axis=1)
player_games['fp_rushing_yards'] = player_games.apply(lambda row: row['rushing_yards'] * .1, axis=1)
player_games['fp_passing_touchdowns'] = player_games.apply(lambda row: row['passing_touchdowns'] * 4, axis=1)
player_games['fp_passing_yards'] = player_games.apply(lambda row: row['passing_yards'] * .04, axis=1)
player_games['fp_passing_interceptions'] = player_games.apply(lambda row: row['passing_interceptions'] * .04, axis=1)
player_games['fp_field_goal_makes'] = player_games.apply(lambda row: row['field_goal_makes'] * 3.5, axis=1)
player_games['fp_point_after_makes'] = player_games.apply(lambda row: row['point_after_makes'] * 1, axis=1)
player_games['fp_field_goal_misses'] = player_games.apply(lambda row: (row['field_goal_attempts'] - row['field_goal_makes']) * -1, axis=1)
player_games['fp_point_after_misses'] = player_games.apply(lambda row: (row['point_after_attemps'] - row['point_after_makes']) * -1, axis=1)

# Create list of fantasy point columns to be summed
list_of_fp_cols = [
    'fp_receiving_touchdowns',
    'fp_receiving_receptions',
    'fp_receiving_yards',
    'fp_rushing_touchdowns',
    'fp_rushing_yards',
    'fp_passing_touchdowns',
    'fp_passing_yards',
    'fp_passing_interceptions',
    'fp_field_goal_makes',
    'fp_point_after_makes',
    'fp_field_goal_misses',
    'fp_point_after_misses'
]


# Create column summing all fantasy point columns row-wise
player_games['fp_total'] = player_games[list_of_fp_cols].sum(axis=1)

In [15]:
# filter out positions not used in fantasy football
player_games = player_games[player_games['position'].isin(['QB','RB','WR','TE','K'])]

In [19]:
player_games['team'].head()

317    NOR
318    DEN
319    DEN
320    DEN
321    DEN
Name: team, dtype: object

In [39]:
player_games['date'] = player_games['date'].astype('str')

In [49]:
# Need to have full opponent names in order to join opponent on the team name from the "teams" DataFrame.

opponent_list = []

for index, row in player_games.iterrows():
    if row['opponent'] == 'MIN':
        opponent_list.append('Minnesota Vikings')
    elif row['opponent'] == 'PIT':
        opponent_list.append('Pittsburgh Steelers')
    elif row['opponent'] == 'NYG':
        opponent_list.append('New York Giants')
    elif row['opponent'] == 'DEN':
        opponent_list.append('Denver Broncos')
    elif row['opponent'] == 'DAL':
        opponent_list.append('Dallas Cowboys')
    elif row['opponent'] == 'GNB':
        opponent_list.append('Green Bay Packers')
    elif row['opponent'] == 'PHI':
        opponent_list.append('Philadelphia Eagles')
    elif row['opponent'] == 'KAN':
        opponent_list.append('Kansas City Chiefs')
    elif row['opponent'] == 'ATL':
        opponent_list.append('Atlanta Falcons')
    elif row['opponent'] == 'CHI':
        opponent_list.append('Chicago Bears')
    elif row['opponent'] == 'WAS':
        opponent_list.append('Washington Redskins')
    elif row['opponent'] == 'SFO':
        opponent_list.append('San Francisco 49ers')
    elif row['opponent'] == 'CIN':
        opponent_list.append('Cincinnati Bengals')
    elif row['opponent'] == 'NOR':
        opponent_list.append('New Orleans Saints')
    elif row['opponent'] == 'BUF':
        opponent_list.append('Buffalo Bills')
    elif row['opponent'] == 'NWE':
        opponent_list.append('New England Patriots')
    elif row['opponent'] == 'MIA':
        opponent_list.append('Miami Dolphins')
    elif row['opponent'] == 'NYJ':
        opponent_list.append('New York Jets')
    elif row['opponent'] == 'SDG':
        opponent_list.append('San Diego Chargers')
    elif row['opponent'] == 'DET':
        opponent_list.append('Detroit Lions')
    elif row['opponent'] == 'HOU':
        if row['date'] < '1997':
            opponent_list.append('Houston Oilers')
        else:
            opponent_list.append('Houston Texans')
    elif row['opponent'] == 'CLE':
        opponent_list.append('Cleveland Browns')
    elif row['opponent'] == 'SEA':
        opponent_list.append('Seattle Seahawks')
    elif row['opponent'] == 'TAM':
        opponent_list.append('Tampa Bay Buccaneers')
    elif row['opponent'] == 'CIN':
        opponent_list.append('Cincinnati Bengals')
    elif row['opponent'] == 'STL':
        if row['date'] < '1988':
            opponent_list.append('St. Louis Cardinals')
        else:
            opponent_list.append('St. Louis Rams')
    elif row['opponent'] == 'BAL':
        if row['date'] < '1984':
            opponent_list.append('Baltimore Colts')
        else:
            opponent_list.append('Baltimore Ravens')
    elif row['opponent'] == 'OAK':
        opponent_list.append('Oakland Raiders')
    elif row['opponent'] == 'IND':
        opponent_list.append('Indianapolis Colts')
    elif row['opponent'] == 'RAM':
        opponent_list.append('Los Angeles Rams')
    elif row['opponent'] == 'ARI':
        opponent_list.append('Arizona Cardinals')
    elif row['opponent'] == 'JAX':
        opponent_list.append('Jacksonville Jaguars')
    elif row['opponent'] == 'CAR':
        opponent_list.append('Carolina Panthers')
    elif row['opponent'] == 'TEN':
        if row['date'] < '1999':
            opponent_list.append('Tennessee Oilers')
        else:
            opponent_list.append('Tennessee Titans')
    elif row['opponent'] == 'RAI':
        opponent_list.append('Los Angeles Raiders')
    elif row['opponent'] == 'PHO':
        opponent_list.append('Phoenix Cardinals')
    elif row['opponent'] == 'BOS':
        opponent_list.append('Boston Patriots')
    elif row['opponent'] == 'LAR':
        opponent_list.append('Los Angeles Rams')
    elif row['opponent'] == 'LAC':
        opponent_list.append('Los Angeles Chargers')
    elif row['opponent'] == 'CRD':
        opponent_list.append('Chicago Cardinals')
    elif row['opponent'] == 'DTX':
        opponent_list.append('Dallas Texans')
    elif row['opponent'] == 'NYT':
        opponent_list.append('New York Titans')
    elif row['opponent'] == 'NYY':
        opponent_list.append('New York Yanks')

In [ ]:
# Add full opponent name as a column in the DataFrame
player_games['full_opponent'] = opponent_list

In [46]:
# Convert the team the player plays for to its full team names for convenience in reading the dataset

team_list = []

for index, row in player_games.iterrows():
    if row['team'] == 'MIN':
        team_list.append('Minnesota Vikings')
    elif row['team'] == 'PIT':
        team_list.append('Pittsburgh Steelers')
    elif row['team'] == 'NYG':
        team_list.append('New York Giants')
    elif row['team'] == 'DEN':
        team_list.append('Denver Broncos')
    elif row['team'] == 'DAL':
        team_list.append('Dallas Cowboys')
    elif row['team'] == 'GNB':
        team_list.append('Green Bay Packers')
    elif row['team'] == 'PHI':
        team_list.append('Philadelphia Eagles')
    elif row['team'] == 'KAN':
        team_list.append('Kansas City Chiefs')
    elif row['team'] == 'ATL':
        team_list.append('Atlanta Falcons')
    elif row['team'] == 'CHI':
        team_list.append('Chicago Bears')
    elif row['team'] == 'WAS':
        team_list.append('Washington Redskins')
    elif row['team'] == 'SFO':
        team_list.append('San Francisco 49ers')
    elif row['team'] == 'CIN':
        team_list.append('Cincinnati Bengals')
    elif row['team'] == 'NOR':
        team_list.append('New Orleans Saints')
    elif row['team'] == 'BUF':
        team_list.append('Buffalo Bills')
    elif row['team'] == 'NWE':
        team_list.append('New England Patriots')
    elif row['team'] == 'MIA':
        team_list.append('Miami Dolphins')
    elif row['team'] == 'NYJ':
        team_list.append('New York Jets')
    elif row['team'] == 'SDG':
        team_list.append('San Diego Chargers')
    elif row['team'] == 'DET':
        team_list.append('Detroit Lions')
    elif row['team'] == 'HOU':
        if row['date'] < '1997':
            team_list.append('Houston Oilers')
        else:
            team_list.append('Houston Texans')
    elif row['team'] == 'CLE':
        team_list.append('Cleveland Browns')
    elif row['team'] == 'SEA':
        team_list.append('Seattle Seahawks')
    elif row['team'] == 'TAM':
        team_list.append('Tampa Bay Buccaneers')
    elif row['team'] == 'CIN':
        team_list.append('Cincinnati Bengals')
    elif row['team'] == 'STL':
        if row['date'] < '1988':
            team_list.append('St. Louis Cardinals')
        else:
            team_list.append('St. Louis Rams')
    elif row['team'] == 'BAL':
        if row['date'] < '1984':
            team_list.append('Baltimore Colts')
        else:
            team_list.append('Baltimore Ravens')
    elif row['team'] == 'OAK':
        team_list.append('Oakland Raiders')
    elif row['team'] == 'IND':
        team_list.append('Indianapolis Colts')
    elif row['team'] == 'RAM':
        team_list.append('Los Angeles Rams')
    elif row['team'] == 'ARI':
        team_list.append('Arizona Cardinals')
    elif row['team'] == 'JAX':
        team_list.append('Jacksonville Jaguars')
    elif row['team'] == 'CAR':
        team_list.append('Carolina Panthers')
    elif row['team'] == 'TEN':
        if row['date'] < '1999':
            team_list.append('Tennessee Oilers')
        else:
            team_list.append('Tennessee Titans')
    elif row['team'] == 'RAI':
        team_list.append('Los Angeles Raiders')
    elif row['team'] == 'PHO':
        team_list.append('Phoenix Cardinals')
    elif row['team'] == 'BOS':
        team_list.append('Boston Patriots')
    elif row['team'] == 'LAR':
        team_list.append('Los Angeles Rams')
    elif row['team'] == 'LAC':
        team_list.append('Los Angeles Chargers')
    elif row['team'] == 'CRD':
        team_list.append('Chicago Cardinals')
    elif row['team'] == 'DTX':
        team_list.append('Dallas Texans')
    elif row['team'] == 'NYT':
        team_list.append('New York Titans')
    elif row['team'] == 'NYY':
        team_list.append('New York Yanks')

304448

In [47]:
# Add full team name as a column in the DataFrame
player_games['full_team'] = team_list

In [48]:
# Reorder columns for convenience

# Put 'full_opponent' column next to 'opponent'
player_games = player_games[['player_id', 'name', 'team', 'full_team', 'position', 'age', 'date',
       'year', 'birth_date', 'birth_place', 'college', 'current_salary',
       'current_team', 'death_date', 'draft_position', 'draft_round',
       'draft_team', 'draft_year', 'height', 'high_school',
       'hof_induction_year', 'weight', 'field_goal_attempts',
       'field_goal_makes', 'game_location', 'game_number', 'game_won',
       'opponent', 'full_opponent', 'opponent_score', 'passing_attempts', 'passing_completions',
       'passing_interceptions', 'passing_rating', 'passing_sacks',
       'passing_sacks_yards_lost', 'passing_touchdowns', 'passing_yards',
       'player_team_score', 'point_after_attemps', 'point_after_makes',
       'receiving_receptions', 'receiving_targets', 'receiving_touchdowns',
       'receiving_yards', 'rushing_attempts', 'rushing_touchdowns',
       'rushing_yards', 'fp_receiving_touchdowns', 'fp_receiving_receptions',
       'fp_receiving_yards', 'fp_rushing_touchdowns', 'fp_rushing_yards',
       'fp_passing_touchdowns', 'fp_passing_yards', 'fp_passing_interceptions',
       'fp_field_goal_makes', 'fp_point_after_makes', 'fp_field_goal_misses',
       'fp_point_after_misses', 'fp_total']]

In [2]:
# Read in opponent dataset
opponents = pd.read_csv('nfl_team_game_logs_2.csv')

C:\Users\bryso\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (72,87,89,91,92,93,94,95,96,97) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
# Select desired columns

opponents = opponents[['Team', 'Season', 'year_of_game', 'week_of_season', 'day_of_week',
       'Date', 'result', 'OT?', 'home_or_away', 'opponent',
       'points_scored', 'opponent_points_scored', 'pass_completions',
       'pass_attempts', 'pass_yards', 'passing_tds', 'interceptions',
       'times_sacked', 'sack_yards_lost', 'passing_yards_per_attempt',
       'completion_percentage', 'qb_rating', 'rushing_attempts',
       'rushing_yards', 'rushing_yards_per_attempt', 'rushing_tds', 'FGM',
       'FGA', 'XPM', 'XPA', 'punts', 'total_punt_yards', '3DConv', '3DAtt',
       '4DConv', '4DAtt', 'ToP', 'start_time',
       'record', '1stDowns', 'TotYd', 'turnovers_lost', '1stDowns_allowed',
       'TotYd_allowed', 'PassY_allowed', 'RushY_allowed',
       'defensive_turnovers', 'expected_pts_offense', 'expected_pts_defense',
       'expected_pts_sp.teams']]

In [6]:
# Create a column for the true number game-of-season played by each team

game_of_season = 0
current_season = opponents['Season'][0]

list_game_of_season = []

for index, row in opponents.iterrows():
    if row['Season'] != current_season:
        game_of_season = 0
        current_season = row['Season']
    
    game_of_season += 1
    
    list_game_of_season.append(game_of_season)

opponents['game_of_season'] = list_game_of_season

In [7]:
# drop columns that don't have enough data - 3DConv, 3DAtt, 4DConv, 4DAtt, ToP, start_time, expected_pts_offense, expected_pts_defense, expected_pts_sp.teams; reorder columns

opponents = opponents[['Team', 'Season', 'year_of_game', 'week_of_season', 'game_of_season', 
       'day_of_week', 'Date', 'result', 'OT?', 'home_or_away', 'opponent',
       'points_scored', 'opponent_points_scored', 'pass_completions',
       'pass_attempts', 'pass_yards', 'passing_tds', 'interceptions',
       'times_sacked', 'sack_yards_lost', 'passing_yards_per_attempt',
       'completion_percentage', 'qb_rating', 'rushing_attempts',
       'rushing_yards', 'rushing_yards_per_attempt', 'rushing_tds', 'FGM',
       'FGA', 'XPM', 'XPA', 'punts', 'total_punt_yards',
       'record', '1stDowns', 'TotYd', 'turnovers_lost', '1stDowns_allowed',
       'TotYd_allowed', 'PassY_allowed', 'RushY_allowed',
       'defensive_turnovers']]

In [8]:
# Fill NaNs

opponents['turnovers_lost'].fillna(0, inplace=True)
opponents['defensive_turnovers'].fillna(0, inplace=True)
opponents['OT?'].fillna('No', inplace=True)
opponents['home_or_away'].fillna('vs', inplace=True)
opponents['1stDowns_allowed'].fillna(0, inplace=True)
opponents['1stDowns'].fillna(0, inplace=True)
opponents['PassY_allowed'].fillna(0, inplace=True)
opponents['RushY_allowed'].fillna(0, inplace=True)

In [9]:
# Create a list of numeric stat columns

numeric_columns = ['points_scored',
       'opponent_points_scored', 'pass_completions', 'pass_attempts',
       'pass_yards', 'passing_tds', 'interceptions', 'times_sacked',
       'sack_yards_lost', 'passing_yards_per_attempt', 'completion_percentage',
       'qb_rating', 'rushing_attempts', 'rushing_yards',
       'rushing_yards_per_attempt', 'rushing_tds', 'FGM', 'FGA', 'XPM', 'XPA',
       'punts', 'total_punt_yards', '1stDowns', 'TotYd',
       'turnovers_lost', '1stDowns_allowed', 'TotYd_allowed', 'PassY_allowed',
       'RushY_allowed', 'defensive_turnovers']

In [10]:
def avg_converter(dataframe, list_of_columns): 
    """Create a cumulative average of each stat column (i.e. the average "up to that point" in the season). 
       The average will reset with each new season."""
    
    for column in list_of_columns: 

            column_sum = 0
            current_season = dataframe['Season'][0] 
            list_column_sum = []

            for index, row in dataframe.iterrows(): 

                if row['Season'] != current_season:
                    column_sum = 0
                    current_season = row['Season']

                column_sum = column_sum + row[column]

                list_column_sum.append(column_sum)
                
            dataframe[column] = list_column_sum / dataframe['game_of_season']

In [11]:
avg_converter(opponents, numeric_columns)

In [12]:
# Make the 'record' column uniform by adding '-0' for each row that has zero ties.

cleaned_record_list = []

for row in opponents['record']:
    if len(row) == 3:
        cleaned_record_list.append(row+'-0')
    elif len(row) == 4:
        cleaned_record_list.append(row+'-0')
    else:
        cleaned_record_list.append(row)
        
opponents['record'] = cleaned_record_list

In [13]:
# Create individual wins, losses, and ties columns

wins_list = []
losses_list = []
ties_list = []


for row in opponents['record']:
    if len(row) == 6: # double digits in either wins or losses
        if row[2] == '-': # the double digits occur in the wins
            wins_list.append(row[0:2])
            losses_list.append(row[3])
            ties_list.append(row[5])
        if row[2] == '1': # the double digits occur in the losses
            wins_list.append(row[0])
            losses_list.append(row[2:4])
            ties_list.append(row[5])
    else: # single digits for wins, losses, and ties
        wins_list.append(row[0])
        losses_list.append(row[2])
        ties_list.append(row[4])


opponents['W'] = wins_list
opponents['L'] = losses_list
opponents['T'] = ties_list

In [15]:
# convert W, L, T columns from str to int

opponents['W'] = opponents['W'].astype('int')
opponents['L'] = opponents['L'].astype('int')
opponents['T'] = opponents['T'].astype('int')

In [16]:
# Create column for win percentage

opponents['win_pct'] = opponents['W'] / opponents['game_of_season']

In [18]:
# Create columns for year, month number and day

month_list = []
day_list = []

for row in opponents['Date']:
    s = str(datetime.strptime(row, '%B %d'))
    month = s[5:7]
    day = s[8:10]
    month_list.append(month)
    day_list.append(day)

opponents['year'] = opponents['year_of_game']
opponents['month'] = month_list
opponents['day'] = day_list

In [19]:
# Create a 'datetime' column

opponents['datetime'] = pd.to_datetime(opponents[['year', 'month', 'day']])

In [20]:
# make the 'datetime' column the first column for convenience

opponents = opponents[['datetime', 'Team', 'Season', 'year_of_game', 'week_of_season', 'game_of_season',
       'day_of_week', 'Date', 'result', 'OT?', 'home_or_away', 'opponent',
       'points_scored', 'opponent_points_scored', 'pass_completions',
       'pass_attempts', 'pass_yards', 'passing_tds', 'interceptions',
       'times_sacked', 'sack_yards_lost', 'passing_yards_per_attempt',
       'completion_percentage', 'qb_rating', 'rushing_attempts',
       'rushing_yards', 'rushing_yards_per_attempt', 'rushing_tds', 'FGM',
       'FGA', 'XPM', 'XPA', 'punts', 'total_punt_yards', 'record', '1stDowns',
       'TotYd', 'turnovers_lost', '1stDowns_allowed', 'TotYd_allowed',
       'PassY_allowed', 'RushY_allowed', 'defensive_turnovers', 'W', 'L', 'T',
       'win_pct', 'month', 'day', 'year']]

In [21]:
# this is to match players['datetime'] with the datetime of the previous week's opponent data
opponents['datetime'] = opponents['datetime'].shift(-1)

# drop the last row of the df
opponents = opponents[:-1]

In [22]:
# Drop the last row of each season - we don't care about the last game of the season because
# for each player's performance, we want to grab the prior week's opponent data. Also the 
# shift has caused the last week of each season to be incorrect.

current_season = opponents['Season'][0]

for index, row in opponents.iterrows():
    if index != len(opponents.index):
        #delete the last row of each season
        if row['Season'] != current_season:
            opponents.drop(index-1, inplace=True)
            current_season = row['Season']

In [23]:
# fix the index, which was skipping each index that was just deleted

opponents = opponents.reset_index(drop=True)

In [ ]:
# Merge 'player_games' and 'opponents' dataframes

player_games = player_games.merge(opponents, how='left', left_on=['date', 'full_opponent'], right_on=['datetime',  'Team'])

In [ ]:
# Remove some unnecessary columns
# Columns removed: 'W', 'L', 'T', 'month', 'day', 'year_y', 'result',
## 'week_of_season', 'game_of_season', 'day_of_week', 'Date', 'OT?', 'home_or_away', 'opponent_y' (all these
# are now off by a week because of the datetime shift up)
player_games = player_games[['player_id', 'name', 'full_team', 'position', 'age',
       'date', 'birth_date', 'birth_place', 'college', 'height',
       'high_school', 'weight', 'field_goal_attempts', 'field_goal_makes',
       'game_location', 'game_number', 'game_won', 'opponent_x',
       'full_opponent', 'opponent_score', 'passing_attempts',
       'passing_completions', 'passing_interceptions', 'passing_rating',
       'passing_sacks', 'passing_sacks_yards_lost', 'passing_touchdowns',
       'passing_yards', 'player_team_score', 'point_after_attemps',
       'point_after_makes', 'receiving_receptions', 'receiving_targets',
       'receiving_touchdowns', 'receiving_yards', 'rushing_attempts_x',
       'rushing_touchdowns', 'rushing_yards_x', 'fp_receiving_touchdowns',
       'fp_receiving_receptions', 'fp_receiving_yards',
       'fp_rushing_touchdowns', 'fp_rushing_yards',
       'fp_passing_touchdowns', 'fp_passing_yards',
       'fp_passing_interceptions', 'fp_field_goal_makes',
       'fp_point_after_makes', 'fp_field_goal_misses',
       'fp_point_after_misses', 'fp_total', 'datetime', 'Team', 'Season',
       'year_of_game',
       'points_scored', 'opponent_points_scored', 'pass_completions',
       'pass_attempts', 'pass_yards', 'passing_tds', 'interceptions',
       'times_sacked', 'sack_yards_lost', 'passing_yards_per_attempt',
       'completion_percentage', 'qb_rating', 'rushing_attempts_y',
       'rushing_yards_y', 'rushing_yards_per_attempt', 'rushing_tds',
       'FGM', 'FGA', 'XPM', 'XPA', 'punts', 'total_punt_yards', 'record',
       '1stDowns', 'TotYd', 'turnovers_lost', '1stDowns_allowed',
       'TotYd_allowed', 'PassY_allowed', 'RushY_allowed',
       'defensive_turnovers','win_pct']]

In [ ]:
# Drop all rows for which there is no opponent data (first week of each season)
player_games = player_games[pd.notnull(player_games['datetime'])]